version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    command:
      - mysqld
      - --max_connections=3000
      - --wait_timeout=600
      - --interactive_timeout=600
      - --thread_cache_size=50
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    environment:
      - MYSQL_DATABASE=jungblog
      - MYSQL_ROOT_PASSWORD=jungblog!2!Q@W#E
    ports:
      - 3306:3306
    volumes:
      - ./bin/datas/mysql/:/var/lib/mysql
    depends_on:
      - redis
    container_name: db

  jungblog:
    build: .
    restart: always
    command: bash -c 'sh /code/jungblog/bin/docker_start.sh'
    ports:
      - "8000:8000"
    volumes:
      - ./collectedstatic:/code/jungblog/collectedstatic
      - ./uploads:/code/jungblog/uploads
      - ./logs:/code/jungblog/logs
    environment:
      - DJANGO_MYSQL_DATABASE=jungblog
      - DJANGO_MYSQL_USER=root
      - DJANGO_MYSQL_PASSWORD=jungblog!2!Q@W#E
      - DJANGO_MYSQL_HOST=db
      - DJANGO_MYSQL_PORT=3306
      - DJANGO_REDIS_URL=redis:6379
      - DJANGO_DEBUG=False
    links:
      - db
      - redis
    depends_on:
      - db
    container_name: jungblog
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./bin/nginx.conf:/etc/nginx/nginx.conf
      - ./uploads:/code/jungblog/uploads
      - ./collectedstatic:/code/jungblog/collectedstatic
    links:
      - jungblog:jungblog
    container_name: nginx

  redis:
    restart: always
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
