version: '3'

services:
  es:
    image: juestnow/elasticsearch-analysis-ik:7.16.1
    container_name: es
    restart: always
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    volumes:
      - ./bin/datas/es/:/usr/share/elasticsearch/data/

  kibana:
    image: kibana:7.13.2
    restart: always
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200

  jungblog:
    build: .
    restart: always
    command: bash -c 'sh /code/jungblog/bin/docker_start.sh'
    ports:
      - "8000:8000"
    volumes:
      - ./collectedstatic:/code/jungblog/collectedstatic
    environment:
      - DJANGO_MYSQL_DATABASE=jungblog
      - DJANGO_MYSQL_USER=root
      - DJANGO_MYSQL_PASSWORD=jungblog!2!Q@W#E
      - DJANGO_MYSQL_HOST=db
      - DJANGO_MYSQL_PORT=3306
      - DJANGO_MEMCACHED_LOCATION=memcached:11211
      - DJANGO_ELASTICSEARCH_HOST=es:9200
    links:
      - db
      - memcached
    depends_on:
      - db
    container_name: jungblog

